---
- name: Create users  and files/dirs in user home directory
  hosts: all
  tasks: 
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
        uid: '{{u}}'
        comment: "{{d}}"
    - name: crate file or dir in user dir
      file: 
        name: "{{e}}"
        state: "{{f}}"
